// import { useEffect } from 'react'
import BackToTop from './BackToTop'
import Footer from './Footer'
import GoogleAnalytics from './GoogleAnalytics'
import Nav from './Nav'
import './globals.css'
import { Prompt, Oxygen } from 'next/font/google'

const oxygen = Oxygen({ subsets: ['latin'], weight: ['300', '400', '700'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icon: '/hidden-talent-icon-arrow.png',
}

export default function RootLayout({ children }) {

  // useEffect(() => {
  //   (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
  //   new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
  //   j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
  //   'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
  //   })(window,document,'script','dataLayer','GTM-K6GQPDW2');
  // })

  return (
    <html lang="en" className={oxygen.className}>
      <head>
        <link rel="icon" href="/hidden-talent-icon.svg" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin='true' />
        <link href="https://fonts.googleapis.com/css2?family=Prompt:wght@400;500;600&display=swap" rel="stylesheet" />
      </head>
      <body className='w-screen max-w-[100vw] overflow-x-clip relative'>
        <BackToTop className="absolute bottom-0 right-0" />
        <Nav />
        {children}
        <Footer />
        <GoogleAnalytics />
      </body>
    </html>
  )
}


// export default function RootLayout({ children }) {
//   return (
//     <html lang="en" className={oxygen.className}>
//       <head>
//         <link rel="icon" href="/hidden-talent-icon.svg" />
//         <link rel="preconnect" href="https://fonts.googleapis.com" />
//         <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin='true' />
//         <link href="https://fonts.googleapis.com/css2?family=Prompt:wght@400;500;600&display=swap" rel="stylesheet" />
//       </head>
//       <body className='max-w-[100vw]'>
//         <div className='grid grid-rows-[auto_1fr_auto] min-h-screen w-screen relative'>
//           <BackToTop className="absolute bottom-0 right-0" />
//           <Nav />
//           {children}
//           <Footer />
//         </div>
//       </body>
//     </html>
//   )
// }
